# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: PC

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonar'
    organization: 'mbrettip'
    scannerMode: 'Other'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean verify sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: default
    mavenVersionOption: 'Default'
- task: SonarCloudAnalyze@1
- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'Sonar'
    organization: 'mbrettip'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
